name: Deploy Automático GDBrasilSolar

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: FTP Deploy Plataforma Solar
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Baixando o código atualizado
      uses: actions/checkout@v4
    
    - name: 🚀 Enviando arquivos via FTP para a Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/ # Envia direto para a raiz do seu domínio gdbrasilsolar.com.br
